/* トップメニューのjs */
function changeSideMenu() {
	document.getElementById("sideMenu1").innerHTML = "<li class='header'>MAIN MENU</li>"
		+ "<li class='treeview'> "
        + "	<a href='#'><i class='fa fa-arrow-circle-o-right'></i> <span>個人情報</span> <i class='fa fa-angle-left pull-right'></i></a> "
        + "	<ul class='treeview-menu'> "
        + "		<li><a href='#' onclick='perSchedule()'>学習スケジュール</a></li> "
        + "		<li><a href='#' onclick='perAnalysis()'>個人分析</a></li> "
        + "		<li><a href='#' onclick='perDataChange()'>個人情報変更</a></li> "
        + "	</ul> "
        + "</li> "
        + "<li class='header'>過去問題集</li>"
        + "<li class='treeview'>"
        + "	<a href='#'><i class='fa fa-arrow-circle-o-right'></i> <span>基本情報</span> <i class='fa fa-angle-left pull-right'></i></a> "
        + "	<ul class='treeview-menu'> "
        + "		<li><a href='#' onclick=''>平成２７年度　秋期</a></li> "
        + "		<li><a href='#' onclick=''>平成２７年度　春期</a></li> "
        + "		<li><a href='#' onclick=''>平成２６年度　秋期</a></li> "
        + "		<li><a href='#' onclick=''>平成２６年度　春期</a></li> "
        + "		<li><a href='#' onclick=''>平成２５年度　秋期</a></li> "
        + "		<li><a href='#' onclick=''>平成２５年度　春期</a></li> "
        + "		<li><a href='#' onclick=''>平成２４年度　秋期</a></li> "
        + "		<li><a href='#' onclick=''>平成２４年度　春期</a></li> "
        + "		<li><a href='#' onclick=''>平成２３年度　秋期</a></li> "
        + "		<li><a href='#' onclick=''>平成２３年度　春期</a></li> "
        + "		<li><a href='#' onclick=''>平成２２年度　秋期</a></li> "
        + "		<li><a href='#' onclick=''>平成２２年度　春期</a></li> "
        + "		<li><a href='#' onclick=''>平成２１年度　秋期</a></li> "
        + "		<li><a href='#' onclick=''>平成２１年度　春期</a></li> "
        + "	</ul> "
        + "</li> "
        + "<li class='treeview'>"
        + "	<a href='#'><i class='fa fa-arrow-circle-o-right'></i> <span>応用情報</span> <i class='fa fa-angle-left pull-right'></i></a> "
        + "	<ul class='treeview-menu'> "
        + "		<li><a href='#' onclick=''>平成２７年度　秋期</a></li> "
        + "		<li><a href='#' onclick=''>平成２７年度　春期</a></li> "
        + "		<li><a href='#' onclick=''>平成２６年度　秋期</a></li> "
        + "		<li><a href='#' onclick=''>平成２６年度　春期</a></li> "
        + "		<li><a href='#' onclick=''>平成２５年度　秋期</a></li> "
        + "		<li><a href='#' onclick=''>平成２５年度　春期</a></li> "
        + "		<li><a href='#' onclick=''>平成２４年度　秋期</a></li> "
        + "		<li><a href='#' onclick=''>平成２４年度　春期</a></li> "
        + "		<li><a href='#' onclick=''>平成２３年度　秋期</a></li> "
        + "		<li><a href='#' onclick=''>平成２３年度　春期</a></li> "
        + "		<li><a href='#' onclick=''>平成２２年度　秋期</a></li> "
        + "		<li><a href='#' onclick=''>平成２２年度　春期</a></li> "
        + "		<li><a href='#' onclick=''>平成２１年度　秋期</a></li> "
        + "		<li><a href='#' onclick=''>平成２１年度　春期</a></li> "
        + "	</ul> "
        + "</li> "
        + "<li class='treeview'> "
        + "	<a href='#'><i class='fa fa-arrow-circle-o-right'></i> <span>過去問題分析</span> <i class='fa fa-angle-left pull-right'></i></a> "
        + "	<ul class='treeview-menu'> "
        + "		<li><a href='#' onclick=''>基本情報</a></li> "
        + "		<li><a href='#' onclick=''>応用情報</a></li> "
        + "	</ul>"
        + "</li> "
        + "<li class='header'>その他</li>"
        + "<li class='treeview'> "
        + "	<a href='#'><i class='fa fa-arrow-circle-o-right'></i> <span>問題作成</span> <i class='fa fa-angle-left pull-right'></i></a> "
        + "	<ul class='treeview-menu'> "
        + "		<li><a href='#' onclick=''>問題メンテナンス</a></li> "
        + "	</ul>"
        + "</li> ";
        
}